name: Deploy Javadoc

permissions:
  contents: write
  
on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy javadoc to Github Pages
        uses: dev-vince/actions-publish-javadoc@v1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          java-version: "17" # Replace with your java version. Default is 17
          java-distribution: "adopt" # The distributor of the target JDK. See https://github.com/actions/setup-java for more information. Defauly is adopt
          project: gradle # The project type. By default maven
          branch: "javadoc" # The branch for the javadoc contents. By default gh-pages
