name: Deploy Javadoc

on:
  push:
    branches:
      - master
    paths: 
        - main/src/java/org/firstinspires/ftc/teamcode/lib
      
      

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 8
          target-folder: .
          project: gradle
